config/routes.rb
Rails.application.routes.draw do
  # apipie
  apipie

  # devise
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  # custom routes
  root to: 'projects#index'
  resources :projects, only: [:show, :new, :create, :edit, :update] do
    get 'collaborate'
    post 'collaborate' => 'projects#process_colaboration'
    patch 'accept' => 'projects#accept_project'
  end

  get 'about' => 'pages#about'

  get 'postulations' => 'projects#postulations'
  get 'refuse' => 'projects#refuse_view'
  post 'refuse' => 'projects#refuse_project'

  post 'comment' => 'comments#create'

  post 'news' => 'news#create'

  # Legacy routes
  # get 'new_project' => 'pages#new_project'
  # get 'project' => 'pages#project'
  # get 'login' => 'pages#login'
  # get 'logout' => 'pages#logout'
end

app/models/project.rb
class Project < ApplicationRecord
  # Enums
  enum status: [:pending, :rejected, :running, :finished, :archived], _suffix: true

  # Associations
  belongs_to :user
  has_many :comments
  has_many :news
  has_many :project_tags
  has_many :tags, through: :project_tags
  has_many :rewards
  has_many :donations

  # Validations
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :deadline, presence: true
  validates :description, presence: true
  validates :financing_description, presence: true
  validates :creators_description, presence: true
  validates :goal, presence: true
  validates :status, presence: true

  # Nested attributes
  # accepts_nested_attributes_for :rewards, reject_if: :all_blank
  accepts_nested_attributes_for :rewards, reject_if: lambda { |attributes| attributes['name'].blank? }

  after_initialize :init

  def init
    self.status ||= 0
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :refuse_view, :refuse_project, :edit, :update, :accept_project, :collaborate, :process_colaboration]
  before_action :authenticate_user!, only: [:new, :create, :collaborate, :refuse_view, :refuse_project, :accept_project, :edit, :update, :process_colaboration]

  api :GET, '/'
  def index
    @projects = Project.where(status: 'running')
  end

  api :GET, '/projects/:id'
  param :id, :number, required: true
  def show
  end

  api :GET, '/projects/new'
  def new
    @project = Project.new
    3.times { @project.rewards.build }
  end

  api :POST, '/projects'
  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      flash[:success] = "Project created succesfully."
      redirect_to @project
    else
      render action: :new
    end
  end

  api :GET, '/projects/:id/edit'
  param :id, :number, required: true
  def edit
  end

  api :PUT, '/projects/'
  def update
    if @project.update(project_params)
      UserMailer.pending_for_review_email(@project).deliver_now
      flash[:success] = "Project updated succesfully. Wait for admin review"
      redirect_to @project
    else
      render action: :edit
    end
  end

  api :GET, '/postulations'
  def postulations
    @pending_projects = Project.where(status: 'pending')
    @rejected_projects = Project.where(status: 'rejected')
  end

  api :GET, '/refuse'
  param :id, :number, required: true
  def refuse_view
  end

  api :POST, '/refuse'
  param :id, :number, required: true
  param :message, String, required: true
  def refuse_project
    @project.update(status: 'rejected')
    UserMailer.rejection_email(@project, rejection_params[:message]).deliver_now
    @pending_projects = Project.where(status: 'pending')
    @rejected_projects = Project.where(status: 'rejected')
    render 'postulations'
  end

  api :PATCH, '/projects/:project_id/accept'
  param :project_id, :number, required: true
  def accept_project
    @project.update(status: 'running')
    @pending_projects = Project.where(status: 'pending')
    @rejected_projects = Project.where(status: 'rejected')
    flash[:success] = "Project accepted, a message has been sent to the owner."
    render 'postulations'
  end

  api :GET, '/projects/:project_id/collaborate'
  param :project_id, :number, required: true
  def collaborate
  end

  api :POST, '/projects/:project_id/collaborate'
  param :project_id, :number, required: true
  def process_colaboration
    @donation = Donation.new(
      user: current_user,
      project: @project,
      amount: collaboration_params[:contribution_amount]
    )
    if @donation.save
      redirect_to project_path(@project)
    else
      render action: :collaborate
    end
  end

  private

    def project_params
      # whitelist params
      params.require(:project).permit(:title, :description, :goal,
        :deadline, :financing_description, :creators_description, :status,
        rewards_attributes: [ :id, :name, :description, :lower_bound,
          :upper_bound, :dispatchable]
      )
    end

    def rejection_params
      params.permit(:message, :id)
    end

    def collaboration_params
      params.permit(:contribution_amount, :project_id)
    end

    def set_project
      if not params[:id].nil?
        @project = Project.find(params[:id])
      else
        @project = Project.find(params[:project_id])
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/collaborate.html.erb
<div class="row">
  <div class="col-md-6 col-sm-8 col-xs-12 col-centered">
    <div class="x_panel tile">
      <div class="x_title">
        <h2>Collaborate to <%= @project.title %></h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br>
        <p>You are about to collaborate to a project and help us change the world! We remind you that there is no small contribution! Please fill the following fields to complete your donation.</p>
        <p>Do not forget to tell us if you are interested in the rewards!</p>
        <p>And we remind you that 5% of your contribution will be offered to one of our partner companies to support their actions of planting trees and create green areas in the work places!</p>
        <br>
        <%= form_tag project_collaborate_path(@project), :method => :post, class: "form-horizontal form-label-left input_mask" do %>
          <label class="col-md-12 col-sm-12 col-xs-12">Amount</label>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <input class="form-control" id="contribution_amount" name="contribution_amount" required="required" placeholder="$" type="text">
          </div>
          <div class="clearfix"></div>
        <br>
        <p>I do want to receive the rewards. <%= check_box :dispatchable, class: "form-control" %></p>
        <br>
        <p>Please, transfer the money to the following account:</p>
        <p><b>Bank</b>: <%= @project.user.bank_accounts.first.bank %></p>
        <p><b>Account Number:</b> <%= @project.user.bank_accounts.first.account%></p>
        <p><b>Account Type:</b> <%= @project.user.bank_accounts.first.account_type == 0 ? "Checking" : "Current" %></p>
        <p><b>Account Owner:</b> <%= @project.user.name %></p>
        <br>
        <!--
          <input type="file" name="proof_paiement" accept=".pdf|image/*">
        <div class="ln_solid" style="margin: 10px"></div>
        -->
        <p style="text-align: center;">
          <button type="submit" class="btn btn-default" style="text-align: center;">Collaborate</button>
        </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h2>Edit <%= @project.title %></h2>
<div class="row">
  <div class="col-md-12 col-xs-12">
    <%= form_for @project, :html => { :class => "form-horizontal form-label-left input_mask"} do |f| %>
    <div class="x_panel">
      <div class="x_title">
        <h2>General Information
        </h2>
        <div class="clearfix"></div>
      </div>

      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this article from being saved:</h2>
      
          <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="x_content">
        <br>
          <label class="control-label col-md-2 col-sm-2 col-xs-12">Title</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <input class="form-control" id="project_name" required="required" placeholder="Enter the name of the project. Remember this is the first thing visitors will see." type="text"> -->
            <%= f.text_field :title, class: "form-control", required: true, placeholder: "Enter the name of the project. Remember this is the first thing visitors will see." %>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Description</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <textarea class="form-control" id="project_description" required="required" placeholder="Describe the purpose of the project." type="text"></textarea> -->
            <%= f.text_area :description, class: "form-control", required: true, placeholder: "Describe the purpose of the project." %>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Financing</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <textarea class="form-control" id="project_financing" required="required" placeholder="Describe why you need financing for your project." type="text"></textarea> -->
            <%= f.text_area :financing_description, class: "form-control", required: true, placeholder: "Describe why you need financing for your project." %>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Project's Creator</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <textarea class="form-control" id="project_creator" required="required" placeholder="Tell the collaborators about you." type="text"></textarea> -->
            <%= f.text_area :creators_description, class: "form-control", required: true, placeholder: "Tell the collaborators about you." %>
          </div>
        </form>

        <div class="x_title" style="margin-top: 20px;">
          <h2>Financial Information</h2>
          <div class="clearfix"></div>
        </div>

        <div class="form-horizontal form-label-left input_mask">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">Financial Objective</label>
          <div class="col-md-3 col-sm-3 col-xs-12 form-general">
            <!-- <input class="form-control" id="financial_objective" required="required" placeholder="$$$" type="text"> -->
            <%= f.number_field :goal, class: "form-control", required: true, placeholder: "$$$" %>
            <span class="form-control-feedback right">CLP</span>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Ending Date</label>
          <div class="col-md-4 col-sm-4 col-xs-12 form-general">
            <!-- <input class="form-control" id="ending_date" required="required" placeholder="dd-mm-yyy" type="text"> -->
            <%= f.date_field :deadline, class: "form-control", required: true, placeholder: "dd-mm-yyyy" %>
          </div>

          <label class="col-md-12 col-sm-12 col-xs-12">Rewards</label>
          <div class="col-md-3 col-sm-3 col-xs-3"><i>Name</i></div>
          <div class="col-md-4 col-sm-4 col-xs-4"><i>Description</i></div>
          <div class="col-md-2 col-sm-2 col-xs-2"><i>Min</i></div>
          <div class="col-md-2 col-sm-2 col-xs-2"><i>Max</i></div>
          <div class="col-md-1 col-sm-1 col-xs-1"><i>Dispatchable</i></div>

          <%= f.fields_for :rewards do |ff| %>
            <div class="col-md-3 col-sm-3 col-xs-3 form-general">
              <!-- <input class="form-control" placeholder="" type="text"> -->
              <%= ff.text_field :name, class: "form-control" %>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.text_field :description, class: "form-control" %>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.number_field :lower_bound, class: "form-control" %>
              <span class="form-control-feedback right hidden-xs">CLP</span>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.number_field :upper_bound, class: "form-control" %>
              <span class="form-control-feedback right hidden-xs">CLP</span>
            </div>
            <div class="col-md-1 col-sm-1 col-xs-1 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.check_box :dispatchable, class: "form-control" %>
            </div>
          <% end %>
          <div class="clearfix"></div>

          <!--
          <label class="col-md-12 col-sm-12 col-xs-12" style="margin-top: 10px; margin-bottom: 0px;">Bank Account</label>
          <div class="col-md-6 col-sm-6 col-xs-12 form-general">
            <input class="form-control" id="bank_name" required="required" placeholder="Bank" type="text">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-general">
            <input class="form-control" id="bank_account_owner" required="required" placeholder="Owner's Name" type="text">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12   form-general">
            <input class="form-control" id="bank_account_number" required="required" placeholder="Account Number" type="text">
          </div>
          -->
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
          <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
            <%= f.hidden_field :status, value: :pending %>
            <%= f.submit '*Update', method: :update, class:"btn btn-primary"%>
          </div>
          <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
            <p class="text-danger" style="margin-top: 10px;">*Updating your project will put it in pending state for admin review </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<h2>Our projects</h2>
<div class="row">
  <% @projects.each do |proyect| %>
      <div class="col-md-3 col-sm-4 col-xs-12">
        <div class="x_panel tile">
          <div class="x_title">
            <h2><%= link_to proyect.title, project_path(id: proyect.id) %></h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div id="vaca_img">
              <%= image_tag "vaca.jpg" %>
            </div>
            <br>
            <table class="contact_list">
              <tbody>
              <tr>
                <td> tags </td>
              </tr>
              <tr>
                <td>Goal: <%= number_to_currency(proyect.goal, precision: 0) %></td>
                <td class="text-right">J-5</td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h2>Create a project</h2>
<div class="row">
  <div class="col-md-12 col-xs-12">
    <%= form_for @project, :html => { :class => "form-horizontal form-label-left input_mask"} do |f| %>
    <div class="x_panel">
      <div class="x_title">
        <h2>General Information
        </h2>
        <div class="clearfix"></div>
      </div>

      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this article from being saved:</h2>
      
          <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="x_content">
        <br>
          <label class="control-label col-md-2 col-sm-2 col-xs-12">Title</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <input class="form-control" id="project_name" required="required" placeholder="Enter the name of the project. Remember this is the first thing visitors will see." type="text"> -->
            <%= f.text_field :title, class: "form-control", required: true, placeholder: "Enter the name of the project. Remember this is the first thing visitors will see." %>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Description</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <textarea class="form-control" id="project_description" required="required" placeholder="Describe the purpose of the project." type="text"></textarea> -->
            <%= f.text_area :description, class: "form-control", required: true, placeholder: "Describe the purpose of the project." %>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Financing</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <textarea class="form-control" id="project_financing" required="required" placeholder="Describe why you need financing for your project." type="text"></textarea> -->
            <%= f.text_area :financing_description, class: "form-control", required: true, placeholder: "Describe why you need financing for your project." %>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Project's Creator</label>
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <!-- <textarea class="form-control" id="project_creator" required="required" placeholder="Tell the collaborators about you." type="text"></textarea> -->
            <%= f.text_area :creators_description, class: "form-control", required: true, placeholder: "Tell the collaborators about you." %>
          </div>
        </form>

        <div class="x_title" style="margin-top: 20px;">
          <h2>Financial Information</h2>
          <div class="clearfix"></div>
        </div>

        <div class="form-horizontal form-label-left input_mask">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">Financial Objective</label>
          <div class="col-md-3 col-sm-3 col-xs-12 form-general">
            <!-- <input class="form-control" id="financial_objective" required="required" placeholder="$$$" type="text"> -->
            <%= f.number_field :goal, class: "form-control", required: true, placeholder: "$$$" %>
            <span class="form-control-feedback right">CLP</span>
          </div>

          <label class="control-label col-md-2 col-sm-2 col-xs-12">Ending Date</label>
          <div class="col-md-4 col-sm-4 col-xs-12 form-general">
            <!-- <input class="form-control" id="ending_date" required="required" placeholder="dd-mm-yyy" type="text"> -->
            <%= f.date_field :deadline, class: "form-control", required: true, placeholder: "dd-mm-yyyy" %>
          </div>

          <label class="col-md-12 col-sm-12 col-xs-12">Rewards</label>
          <div class="col-md-3 col-sm-3 col-xs-3"><i>Name</i></div>
          <div class="col-md-4 col-sm-4 col-xs-4"><i>Description</i></div>
          <div class="col-md-2 col-sm-2 col-xs-2"><i>Min</i></div>
          <div class="col-md-2 col-sm-2 col-xs-2"><i>Max</i></div>
          <div class="col-md-1 col-sm-1 col-xs-1"><i>Dispatchable</i></div>

          <%= f.fields_for :rewards do |ff| %>
            <div class="col-md-3 col-sm-3 col-xs-3 form-general">
              <!-- <input class="form-control" placeholder="" type="text"> -->
              <%= ff.text_field :name, class: "form-control" %>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.text_field :description, class: "form-control" %>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.number_field :lower_bound, class: "form-control" %>
              <span class="form-control-feedback right hidden-xs">CLP</span>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.number_field :upper_bound, class: "form-control" %>
              <span class="form-control-feedback right hidden-xs">CLP</span>
            </div>
            <div class="col-md-1 col-sm-1 col-xs-1 form-general">
              <!-- <input class="form-control" placeholder="$$$" type="text"> -->
              <%= ff.check_box :dispatchable, class: "form-control" %>
            </div>
          <% end %>
          <div class="clearfix"></div>

          <!--
          <label class="col-md-12 col-sm-12 col-xs-12" style="margin-top: 10px; margin-bottom: 0px;">Bank Account</label>
          <div class="col-md-6 col-sm-6 col-xs-12 form-general">
            <input class="form-control" id="bank_name" required="required" placeholder="Bank" type="text">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12 form-general">
            <input class="form-control" id="bank_account_owner" required="required" placeholder="Owner's Name" type="text">
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12   form-general">
            <input class="form-control" id="bank_account_number" required="required" placeholder="Account Number" type="text">
          </div>
          -->
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
          <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/postulations.html.erb
<h2>Postulations List</h2>
<div class="row">
  <% @pending_projects.each do |project| %>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <table class="contact_list">
        <td><%= link_to project.title, project_path(id: project.id) %></td>
        <td><%= project.description %></td>
        <td><%= number_to_currency(project.goal, precision: 0) %></td>
        <td width="100px;"><%= project.deadline.strftime('%d-%m-%y') %></td>
        <td><b><%= link_to 'Accept', project_accept_path(project_id: project.id), method: :patch,
                             class:"btn btn-round btn-success", style:"text-align: center;"%></b></td>
        <td><b><%= link_to 'Refuse', refuse_path(id: project.id), method: :get,
                             class:"btn btn-round btn-danger", style:"text-align: center;"%></b></td>
      </table>
    </div>
  <% end %>
</div>
<h2>Rejected Projects</h2>
<div class="row">
  <% @rejected_projects.each do |project| %>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <table class="contact_list">
          <td><%= link_to project.title, project_path(id: project.id) %></td>
          <td><%= project.description %></td>
          <td><%= number_to_currency(project.goal, precision: 0) %></td>
          <td width="100px;"><%= project.deadline.strftime('%d-%m-%y') %></td>
          <td><b><%= link_to 'Accept', project_accept_path(project_id: project.id), method: :patch,
                              class:"btn btn-round btn-success", style:"text-align: center;"%></b></td>
          <td><b><%= link_to 'Refuse', refuse_path(id: project.id), method: :get,
                             class:"btn btn-round btn-danger", style:"text-align: center;"%></b></td>
        </table>
      </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<h2><%= @project.title %></h2>
<div class="row">

  <div class="col-md-9 col-sm-8 col-xs-12">
    <div class="x_panel tile">
      <div class="x_title">
        <!-- LINK TO PROJECT'S DESCRIPTION-->
        <h2>Support My Project</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="project_img">
          <%= image_tag "vaca.jpg" %>
        </div>
        <br>
        <div class="x_title">
          <h3>About the project</h3>
          <div class="clearfix"></div>
        </div>
        <div><%= @project.description %></div>

        <div class="x_title">
          <h3>About the financing</h3>
          <div class="clearfix"></div>
        </div>
        <div><%= @project.financing_description %></div>

        <div class="x_title">
          <h3>About us</h3>
          <div class="clearfix"></div>
        </div>
        <div><%= @project.creators_description %></div>
      </div>
    </div>
  </div>
  <% if current_user %>
      <% if current_user == @project.user %>
          <div class="col-md-3 col-sm-4 col-xs-4">
            <div class="row">
              <div class="x_panel tile">
                <div class="x_title">
                  <h3>Edit Your Project</h3>
                </div>
                <div class="x_content">
                  <div style="text-align: center;">
                    <p style="text-align: center;">Status: <%= @project.status %></p>
                    <%= button_to 'Edit', edit_project_path(id: @project.id), method: :get,
                                  type: "submit", class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
  <% end %>
  <div class="col-md-3 col-sm-4 col-xs-4">
    <div class="row">
      <div class="x_panel tile">
        <div class="x_content">
          <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <p style="font-size: 36px; text-align: center; color: green;"><%= '%.1f' % (100 * @project.donations.sum(:amount) / @project.goal) %>%</p>
          </div>
          <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <p style="text-align: center;"><b><%= number_to_currency(@project.donations.sum(:amount)) %></b></p>
            <p style="text-align: center;">collected out of</p>
            <p style="text-align: center;"><%= number_to_currency(@project.goal) %></p>
          </div>
          <div class="col-md-12 col-md-12 col-sm-12 col-xs-12">
            <div class="ln_solid" style="margin: 10px"></div>
            <p style="text-align: center;">Deadline: <%= (@project.deadline.strftime("%d-%m-%Y")) %></p>
            <div class="ln_solid" style="margin: 10px"></div>
          </div>
          <p style="text-align: center;">
            <%= link_to "Collaborate", project_collaborate_path(@project), class: "btn btn-success", style: "text-align: center;" %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-4 col-xs-4">
    <div class="row">
      <div class="x_panel tile">
        <div class="x_title">
          <h3>Contact</h3>
        </div>
        <!-- LINK TO POSTULANTE USER-->
        <div class="x_content">
          <p style="text-align: center;"><%= @project.user.name %></p>
          <p style="text-align: center;">Email: <%= @project.user.email %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-4 col-xs-4">
    <div class="row">
      <div class="x_panel tile">
        <div class="x_title">
          <h3>We offer...</h3>
        </div>
        <div class="x_content">
          <!-- LINK TO CONTERPARTS-->
          <% @project.rewards.each do |reward| %>
              <p style=" color: green;">For <%=number_to_currency(reward.lower_bound)%> to <%=number_to_currency(reward.upper_bound)%>:</p>
              <p><%= reward.name %></p>
              <div class="ln_solid" style="margin: 10px"></div>
          <% end %>
          <p style="text-align: center;">
            <%= link_to "Collaborate", project_collaborate_path(@project), class: "btn btn-success", style: "text-align: center;" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-9 col-sm-8 col-xs-12">
    <!-- NEWS -->
    <div class="x_panel">
      <% if current_user and current_user.id == @project.user.id %>
        <div class="x_title">
          <h2>Post a News</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <%= form_with(model: News.new, url: news_path(id: @project.id), method: :post) do |f|%>
                <div class="form-group">
                  <div class="control-label col-md-2 col-sm-2 col-xs-12">Headline</div>
                  <%= f.text_field :headline, class:"form-control",
                                    placeholder:"The news headline", type:"text"  %>
                </div>
                <div class="form-group">
                  <div class="control-label col-md-2 col-sm-2 col-xs-12">Body</div>
                  <%= f.text_area :body, class:"form-control",
                                    placeholder:"The news body", type:"text"  %>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-10">
                  <%= f.submit 'Post', class:"btn btn-success"%>
                </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <% if @project.news.length > 0 %>
        <div class="x_content">
          <h2>News</h2>
          <% @project.news.each do |news| %>
              <h3><%= news.headline %></h3>
              <p><%= news.body %></p>
              <div class="ln_solid" style="margin: 10px"></div>
          <% end %>
        </div>
      <% end %>
      </div>

    <!-- COMMENTS -->
    <div class="x_panel">
      <% if current_user %>
        <div class="x_title">
          <h2>Leave a Comment</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="col-md-10 col-sm-10 col-xs-12 form-general">
            <%= form_with(model: Comment.new, url: comment_path(id: @project.id), method: :post) do |f|%>
                <div class="form-group">
                  <div class="control-label col-md-2 col-sm-2 col-xs-12">Message</div>
                  <%= f.text_area :body, class:"form-control",
                                    placeholder:"Leave a comment for the project comunity.", type:"text"  %>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-10">
                  <%= f.submit 'Comment', class:"btn btn-success"%>
                </div>
            <% end %>
          </div>
        </div>
      <% end %>

        <div class="x_content">
          <% @project.comments.each do |comment| %>
              <p style=" color: green;"><%= comment.user.name %>:</p>
              <p><%= comment.body %></p>
              <div class="ln_solid" style="margin: 10px"></div>
          <% end %>
        </div>
      </div>
  </div>
</div>