config/routes.rb
Rails.application.routes.draw do
  # apipie
  apipie

  # devise
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  # custom routes
  root to: 'projects#index'
  resources :projects, only: [:show, :new, :create, :edit, :update] do
    get 'collaborate'
    post 'collaborate' => 'projects#process_colaboration'
    patch 'accept' => 'projects#accept_project'
  end

  get 'about' => 'pages#about'

  get 'postulations' => 'projects#postulations'
  get 'refuse' => 'projects#refuse_view'
  post 'refuse' => 'projects#refuse_project'

  post 'comment' => 'comments#create'

  post 'news' => 'news#create'

  # Legacy routes
  # get 'new_project' => 'pages#new_project'
  # get 'project' => 'pages#project'
  # get 'login' => 'pages#login'
  # get 'logout' => 'pages#logout'
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li><%= value %></li>
      </ul>
    </div>
<% end %>

app/views/layouts/_top_nav.html.erb
<!--topnav-->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="">
            <%= link_to "Sign in", new_user_session_path %>
          </li>
          <li class="">
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
        <% end %>

      </ul>
    </nav>

  </div>
</div>
<!--/topnav-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaVaca</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="nav-md">
    <%= render 'layouts/messages' %>
    <div class="container body" style="margin:0; padding: 0; width:100%">
      <div class="main_container">
        <!--sidebar-->
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border:0">
              <a class="site_title">
                <span>La Vaca</span>
              </a>
            </div>
            <div id="sidebar-menu" class="main_menu_side main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="/">Home</a></li>
                  <li><a href="<%= new_project_path %>">Propose Project</a></li>
                </ul>
              </div>
              <div class="menu_section">
                <h3>Other</h3>
                <ul class="nav side-menu">
                  <li><a href="/about">About Us</a></li>
                </ul>
              </div>
              <% if current_user %>
                <% if current_user.admin_role? %>
                      <div class="menu_section">
                    <h3>Admin Section</h3>
                    <ul class="nav side-menu">
                      <li><a href="/postulations">Postulations List</a></li>
                    </ul>
                  </div>
                <% elsif current_user.normal_role? and !current_user.projects.empty? %>
                      <div class="menu_section">
                        <h3>Accepted Projects</h3>
                        <ul class="nav side-menu">
                          <% current_user.projects.where(status: 'running').each do |project| %>
                              <li><%= link_to project.title, project_path(id: project.id) %></li>
                          <% end %>
                        </ul>
                      </div>
                    <div class="menu_section">
                      <h3>Pending Projects</h3>
                      <ul class="nav side-menu">
                        <% current_user.projects.where(status: 'pending').each do |project| %>
                            <li><%= link_to project.title, project_path(id: project.id) %></li>
                        <% end %>
                      </ul>
                    </div>
                    <div class="menu_section">
                      <h3>Rejected Projects</h3>
                      <ul class="nav side-menu">
                        <% current_user.projects.where(status: 'rejected').each do |project| %>
                            <li><%= link_to project.title, project_path(id: project.id) %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <!--/sidebar-->
        <%= render 'layouts/top_nav' %>
        <!--page content-->
        <div class="right_col" role="main">
          <%= yield %>
        </div>
        <!--/page content-->
      </div>
    </div>
  </body>
</html>